package gui;

import conexionBD.Conexion;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony
 */
public class PantallaLogeo extends javax.swing.JFrame {

    PantallaMenu pantallaMenu = new PantallaMenu();
    PantallaDeposito pd = new PantallaDeposito();
    ImageIcon imagen = new ImageIcon(getClass().getResource("/img/atm.png"));
    Conexion conexion = new Conexion();
    static int cedula = 0;
    String contraseña="", sql="", sqlCuentaExiste="";
    boolean encontrado;
    int xMouse, yMouse;
    
    public PantallaLogeo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        crearCuentaText = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        cedulaText = new javax.swing.JTextField();
        contrasenaText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnMover = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoText.setBackground(new java.awt.Color(102, 102, 102));
        logoText.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        logoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atm.png"))); // NOI18N
        jPanel1.add(logoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 100));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cédula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        crearCuentaText.setBackground(new java.awt.Color(0, 0, 0));
        crearCuentaText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        crearCuentaText.setForeground(new java.awt.Color(102, 102, 102));
        crearCuentaText.setText("Crear cuenta");
        crearCuentaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearCuentaTextMouseClicked(evt);
            }
        });
        jPanel1.add(crearCuentaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        btn.setBackground(new java.awt.Color(173, 193, 137));
        btn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btn.setForeground(new java.awt.Color(0, 0, 0));
        btn.setText("Ingresar");
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt);
            }
        });
        jPanel1.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 140, 30));

        cedulaText.setBackground(new java.awt.Color(255, 255, 255));
        cedulaText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cedulaText.setBorder(null);
        jPanel1.add(cedulaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 30));

        contrasenaText.setBackground(new java.awt.Color(255, 255, 255));
        contrasenaText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        contrasenaText.setBorder(null);
        jPanel1.add(contrasenaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 130, 10));

        btnMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnMoverMouseDragged(evt);
            }
        });
        btnMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMoverMousePressed(evt);
            }
        });
        jPanel1.add(btnMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 470, 30));

        btnSalir.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(173, 193, 137));
        btnSalir.setText("x");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseClicked
        
        //Condicionales para espacios vacíos y letras en espacio de cédula.
        if(cedulaText.getText().trim().isEmpty() || contrasenaText.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
        }else if(!cedulaText.getText().trim().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "El campo de cédula sólo puede contener números.");
        }else{
            cedula = Integer.parseInt(cedulaText.getText());
            contraseña = contrasenaText.getText();

            //Switch en casos de ingresar o crear cuenta.
            switch(btn.getText()){
                case "Ingresar":
                    encontrado = false;
                    sql = "select * from clientes where cedula_cliente='"+cedula+"' and contrasena='"+contraseña+"'";
                    
                    //Proceso de conexion con la base de datos para ingresar al menú del servicio.
                    try{
                        conexion.conectar();
                        Statement st = conexion.cn.createStatement();
                        ResultSet rs = st.executeQuery(sql);

                        while(rs.next()){
                            encontrado = true;
                            pantallaMenu.show();
                            this.hide();
                        }
                        if(encontrado == false){
                            JOptionPane.showMessageDialog(null, "Credenciales no válidas o el usuario no se ha registrado en el sistema.");
                        }
                        conexion.desconectar();
                    }catch(SQLException ex){
                        System.out.println(ex);
                    }
                    break;

                case "Crear Cuenta":
                    sql = "insert into clientes (cedula_cliente,contrasena) values ('"+cedula+"','"+contraseña+"')";
                    sqlCuentaExiste ="select * from clientes where cedula_cliente='"+cedula+"'";
                    
                    //Proceso de conexion con la base de datos para insertar nueva cuenta.
                    try{
                        conexion.conectar();
                        Statement st = conexion.cn.createStatement();
                        ResultSet rs = st.executeQuery(sqlCuentaExiste);
                        if(rs.next()){
                            JOptionPane.showMessageDialog(null, "La cédula ingresada ya se encuentra registrada en el sistema.");
                        }else{
                            st.executeUpdate(sql); 
                            JOptionPane.showMessageDialog(null, "Cliente ingresado al sistema.");
                            logoText.setIcon(imagen);
                            logoText.setText("");
                            btn.setText("Ingresar");
                            crearCuentaText.setText("Crear cuenta");
                            conexion.desconectar();
                        }
                    }catch(SQLException ex){
                        System.out.println(ex);
                    }
                    break;  
            }  
            cedulaText.setText("");
            contrasenaText.setText("");
        }
    }//GEN-LAST:event_btnMouseClicked

    private void crearCuentaTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCuentaTextMouseClicked
        cedulaText.setText("");
        contrasenaText.setText("");
        switch(crearCuentaText.getText()){
            case "Atrás":
                logoText.setIcon(imagen);
                logoText.setText("");
                btn.setText("Ingresar");
                crearCuentaText.setText("Crear cuenta");
                break;
            default:
                logoText.setIcon(null);
                logoText.setText("Crear Nueva Cuenta");
                btn.setText("Crear Cuenta");
                crearCuentaText.setText("Atrás");
                break;
        }
    }//GEN-LAST:event_crearCuentaTextMouseClicked

    private void btnMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoverMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_btnMoverMousePressed

    private void btnMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_btnMoverMouseDragged

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        Object [] opciones = {"Sí","No"};
        int salir = JOptionPane.showOptionDialog(null, "¿Desea salir?", null, JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opciones, null);
        if(salir == JOptionPane.YES_OPTION){
            System.exit(0);
        }    
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLogeo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel btnMover;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JTextField cedulaText;
    private javax.swing.JTextField contrasenaText;
    private javax.swing.JLabel crearCuentaText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoText;
    // End of variables declaration//GEN-END:variables
}
