package gui;

import conexionBD.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Anthony
 */
public class PantallaRetiro extends javax.swing.JFrame {
    
    Conexion conexion = new Conexion();
    int cantidad, cedula =0, fondos;
    String sql="", checkCedula="", sqlTransaccion="";
    int xMouse, yMouse;

    /**
     * Creates new form PantallaRetirar
     */
    public PantallaRetiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JLabel();
        retiroText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnRetirar = new javax.swing.JButton();
        btnMover = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Retiro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 50));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite la cantidad a retirar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 500, 20));

        btnAtras.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(102, 102, 102));
        btnAtras.setText("Atrás");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        retiroText.setBackground(new java.awt.Color(255, 255, 255));
        retiroText.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        retiroText.setForeground(new java.awt.Color(0, 0, 0));
        retiroText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        retiroText.setBorder(null);
        jPanel1.add(retiroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 160, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 130, 10));

        btnRetirar.setBackground(new java.awt.Color(173, 193, 137));
        btnRetirar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(0, 0, 0));
        btnRetirar.setText("Retirar");
        btnRetirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarMouseClicked(evt);
            }
        });
        jPanel1.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 90, 30));

        btnMover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnMoverMouseDragged(evt);
            }
        });
        btnMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMoverMousePressed(evt);
            }
        });
        jPanel1.add(btnMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 470, 30));

        btnSalir.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(173, 193, 137));
        btnSalir.setText("x");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        PantallaMenu pm = new PantallaMenu();
        pm.show();
        this.hide();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnRetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarMouseClicked
        
        //Condicionales para espacios vacíos y letras en espacio de cédula.
        if(retiroText.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.");
        }else if(!retiroText.getText().trim().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "El campo sólo puede contener números.");
        }else{

            fondos = 0;
            cantidad = Integer.parseInt(retiroText.getText());
            PantallaLogeo pl = new PantallaLogeo();
            checkCedula = "select * from cuentas where cedula_cliente='"+pl.cedula+"'";

            //Proceso de conexion con la base de datos para ingresar al menú del servicio.
            try{
                conexion.conectar();
                Statement st = conexion.cn.createStatement();
                ResultSet rs = st.executeQuery(checkCedula);

                if(rs.next()){
                    fondos = Integer.parseInt(rs.getString("fondos"));
                }
                if(cantidad>fondos){
                    JOptionPane.showMessageDialog(null, "La cantidad que quiere retirar es mayor de lo que posee su cuenta.");
                }else{
                    sqlTransaccion = "insert into transacciones (cedula_cliente,tipo_transaccion,cantidad) values ('"+pl.cedula+"','Retiro','"+cantidad+"')";
                    cantidad=fondos-cantidad;
                    sql = "insert into cuentas (cedula_cliente,fondos) values('"+pl.cedula+"','"+cantidad+"') on duplicate key update fondos='"+cantidad+"'";
                    st.executeUpdate(sql);
                    st.executeUpdate(sqlTransaccion);
                    JOptionPane.showMessageDialog(null, "Retiro realizado correctamente.");
                }
                conexion.desconectar();
            }catch(SQLException ex){
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btnRetirarMouseClicked

    private void btnMoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoverMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_btnMoverMousePressed

    private void btnMoverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_btnMoverMouseDragged

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        Object [] opciones = {"Sí","No"};
        int salir = JOptionPane.showOptionDialog(null, "¿Desea salir?", null, JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opciones, null);
        if(salir == JOptionPane.YES_OPTION){
            System.exit(0);
        }    
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRetiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnMover;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField retiroText;
    // End of variables declaration//GEN-END:variables
}
